# Generated by Django 2.2.3 on 2019-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('by_info', models.CharField(max_length=15)),
                ('Product_url', models.CharField(max_length=1000)),
                ('Product_img', models.CharField(max_length=1000)),
                ('Product_price', models.CharField(max_length=10)),
                ('rating', models.CharField(max_length=15)),
                ('total_review', models.CharField(max_length=15)),
                ('ans_ask', models.CharField(max_length=15)),
                ('prod_des', models.CharField(max_length=800)),
                ('feature', models.CharField(max_length=1000)),
                ('cust_review', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('page_no', models.IntegerField()),
            ],
        ),
    ]
